### PR TITLE
Bump Swift Argument Parser to stable

### PR DESCRIPTION
**Pull request by uhooi**
## Reference

- https://github.com/apple/swift-argument-parser/releases/tag/1.0.1

### CODE REVIEW

**Comment by swiftyfinch** [comment]
Hello! I need this changes too

**Review by thii — APPROVED** [review]
Thanks @uhooi!

**Comment by swiftyfinch** [comment]
Hello @thii!
I wonder when you are planning to bump the new version?

**Comment by thii** [comment]
Released!

**Pull request merged**
